AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    PathBinder Payment Gateway API

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Runtime: nodejs8.10
        Timeout: 30
        Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
            Variables:
                NODE_ENV: !Ref StageNameParam
                AWS_DEPLOYED_REGION: !Ref "AWS::Region"
                PAYMENT_GATEWAY_TABLE: !Sub "pbpaymentgateway${StageNameParam}"
                PAYMENT_PROCESSOR_KEY: !Ref ProcessorApiKeyParam
        Tags:
            Application: PathBinder
            Purpose: PaymentGateway

Parameters:
    StageNameParam:
        Type: String
        Default: qa
        Description: API Gateway stage to deploy to
    ProcessorApiKeyParam:
        Type: String
        Description: Secret Key for the payment processor API

Resources:

    PathBinderSamFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            Description: PathBinder Payment Gateway API Controller
            CodeUri: ./
            Handler: lambda.handler
            Policies:
              - AWSLambdaBasicExecutionRole
              - !Ref PathBinderLambdaManagedPolicy
            Events:
                ApiProxy:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /{proxy+}
                        Method: ANY
                        RestApiId: !Ref ApiGatewayApi

    PathBinderLambdaManagedPolicy:
        Type: AWS::IAM::ManagedPolicy
        Properties:
            Description: Allows the application to access the PathBinder DynamoDB table
            Path: "/application/"
            PolicyDocument:
                Version: "2012-10-17"
                Statement:
                    -
                        Sid: "DynamoDBAccess"
                        Effect: "Allow"
                        Action:
                          - "dynamodb:BatchGetItem"
                          - "dynamodb:BatchWriteItem"
                          - "dynamodb:DeleteItem"
                          - "dynamodb:DescribeTable"
                          - "dynamodb:GetItem"
                          - "dynamodb:PutItem"
                          - "dynamodb:Query"
                          - "dynamodb:Scan"
                          - "dynamodb:UpdateItem"
                        Resource: !GetAtt PathBinderDynamoDB.Arn
            ManagedPolicyName: !Sub "PathBinderPaymentGateway-${AWS::StackName}"

    PathBinderDynamoDB:
      Type: AWS::Serverless::SimpleTable
      Properties:
        TableName: !Sub "pbpaymentgateway${StageNameParam}"
        PrimaryKey:
          Name: username
          Type: String
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        Tags:
          Application: PathBinder
          Purpose: PaymentGateway
        SSESpecification:
          SSEEnabled: true

    ApiGatewayApi:
        Type: AWS::Serverless::Api
        Properties:
          StageName: !Ref StageNameParam
          DefinitionBody:
              swagger: "2.0"
              info:
                version: "2018-07-17T17:04:10Z"
                title:
                  Fn::Sub: "PBPaymentGateway${StageNameParam}"
              schemes:
              - "https"
              paths:
                /{proxy+}:
                  x-amazon-apigateway-any-method:
                    produces:
                    - "application/json"
                    parameters:
                    - name: "proxy"
                      in: "path"
                      required: true
                      type: "string"
                    responses: {}
                    security:
                    - api_key: []
                    x-amazon-apigateway-integration:
                      uri:
                        Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PathBinderSamFunction.Arn}/invocations"
                      responses:
                        default:
                          statusCode: "200"
                      passthroughBehavior: "when_no_match"
                      httpMethod: "POST"
                      cacheKeyParameters:
                      - "method.request.path.proxy"
                      contentHandling: "CONVERT_TO_TEXT"
                      type: "aws_proxy"
              securityDefinitions:
                api_key:
                  type: "apiKey"
                  name: "x-api-key"
                  in: "header"

    ApiGatewayUsagePlan:
      Type: AWS::ApiGateway::UsagePlan
      DependsOn:
      - ApiGatewayApiStage
      Properties:
        ApiStages:
        - ApiId: !Ref ApiGatewayApi
          Stage: !Ref StageNameParam
        Description: "Usage plan to allow API Key access to the payment gateway"
        UsagePlanName: PaymentGatewayAccess


Outputs:

    PaymentGatewayApiUrl:
      Description: "Payment Gateway API endpoint URL for this deployment"
      Value: !Sub "https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/${StageNameParam}"

    CreateAPIKeyInstructions:
      Description: "Run these commands from the command line to generate API keys for consuming applications. **BE SURE to change 'APPLICATION_NAME' to your actual application name"
      Value: !Sub "KEY_ID=`aws apigateway create-api-key --enabled --name APPLICATION_NAME --query 'id' --output text` && aws apigateway create-usage-plan-key --key-type \"API_KEY\" --usage-plan-id ${ApiGatewayUsagePlan} --key-id $KEY_ID && aws apigateway get-api-key --api-key $KEY_ID --include-value --output text --query 'value'"
